name: check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ "*" ]
    types: [synchronize, opened, reopened, edited]
  workflow_dispatch:

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        compilation_mode:
          - 'fastbuild'
          - 'opt'
        toolchain:
          #- 'gcc12' # GCC12 has missing support for C++23
          - 'clang19'
        os:
          - 'ubuntu-latest'
          - 'macos-latest'
        feature:
          - ''
        include:
          - compilation_mode: 'fastbuild'
            toolchain: 'clang19'
            os: 'ubuntu-latest'
            feature: 'asan'
          - compilation_mode: 'fastbuild'
            toolchain: 'clang19'
            os: 'ubuntu-latest'
            feature: 'tsan'
          - compilation_mode: 'fastbuild'
            toolchain: 'clang19'
            os: 'ubuntu-latest'
            feature: 'ubsan'
    runs-on: ${{ matrix.os }}
    env:
      PROFILE: profile-${{ matrix.os }}-${{ matrix.compilation_mode }}-${{ matrix.toolchain }}-${{ matrix.feature }}.gz
    steps:
    - uses: actions/checkout@v4
    - uses: ./.github/actions/ci-env-setup
      with:
        buildbuddy-api-key: ${{ secrets.BUILDBUDDY_API_KEY }}
    - run: |
        bazel \
          test \
          --profile=$PROFILE \
          --compilation_mode=${{ matrix.compilation_mode }} \
          --extra_toolchains=//tools:${{ matrix.toolchain }}_toolchain \
          --features=${{ matrix.feature }} \
          //...

        bazel analyze-profile $PROFILE
    - uses: actions/upload-artifact@v4
      with:
        name: ${{ env.PROFILE }}
        path : ${{ env.PROFILE }}

  coverage:
    runs-on: ubuntu-latest
    env:
      PROFILE: profile-coverage.gz
    steps:
    - uses: actions/checkout@v4
    - uses: ./.github/actions/ci-env-setup
      with:
        buildbuddy-api-key: ${{ secrets.BUILDBUDDY_API_KEY }}
    - run: |
        bazel run --profile=$PROFILE \
          //tools:coverage

        bazel analyze-profile $PROFILE
    - uses: actions/upload-artifact@v4
      with:
        name: ${{ env.PROFILE }}
        path : ${{ env.PROFILE }}
    - uses: codecov/codecov-action@v4
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: ./bazel-out/_coverage/_coverage_report.dat
        fail_ci_if_error: true

  format:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: ./.github/actions/ci-env-setup
      with:
        buildbuddy-api-key: ${{ secrets.BUILDBUDDY_API_KEY }}
    - run: |
        bazel run //tools:format.check

  clang-tidy-targets:
    runs-on: ubuntu-latest
    outputs:
      targets: ${{ steps.query.outputs.targets}}
    steps:
    - uses: actions/checkout@v4
    - uses: ./.github/actions/ci-env-setup
      with:
        buildbuddy-api-key: ${{ secrets.BUILDBUDDY_API_KEY }}
    - id: query
      run: |
        targets=$(\
          bazel cquery \
            --extra_toolchains=//tools:clang19_toolchain \
            --output starlark \
            --starlark:expr='repr(target).split(" ")[-1].removesuffix(">") if "CcInfo" in providers(target).keys() and not repr(target).startswith("<alias") else ""' \
            -- \
            //... | xargs)

        echo "targets=[\"${targets// /\",\"}\"]" >> $GITHUB_OUTPUT

  clang-tidy:
    runs-on: ubuntu-latest
    needs:
      - clang-tidy-targets
    strategy:
      fail-fast: false
      matrix:
        target: ${{ fromJson(needs.clang-tidy-targets.outputs.targets) }}
    steps:
    - uses: actions/checkout@v4
    - uses: ./.github/actions/ci-env-setup
      with:
        buildbuddy-api-key: ${{ secrets.BUILDBUDDY_API_KEY }}
    - run: |
        bazel run //tools:clang-tidy -- ${{ matrix.target }}

  lint:
    runs-on: ubuntu-latest
    needs:
      - clang-tidy
    steps:
    - uses: actions/checkout@v4
    - uses: ./.github/actions/ci-env-setup
      with:
        buildbuddy-api-key: ${{ secrets.BUILDBUDDY_API_KEY }}
    - run: |
        bazel run //tools:lint

  # https://emmer.dev/blog/skippable-github-status-checks-aren-t-really-required/
  # https://github.com/marketplace/actions/alls-green
  all:
    runs-on: ubuntu-latest
    if: always()
    needs:
      - test
      - coverage
      - format
      - lint
    steps:
    - uses: re-actors/alls-green@release/v1
      with:
        jobs: ${{ toJSON(needs) }}
